version: '3.8'

volumes:
    db:
    caddy_data:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432" # assumes firewall
    volumes:
      - db:/var/lib/postgresql/data

  frontend:
    restart: always
    build: ./frontend
    env_file: .env.frontend

  caddy:
    build: ./caddy
    volumes:
      - caddy_data:/data
    ports:
      - "80:80"
      - "443:443"

  api:
    build: ./backend
    env_file: .env.backend
