version: '3.8'

volumes:
    db:

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  frontend:
    restart: unless-stopped
    build: ./frontend
    env_file: frontend/.env
    networks:
      - caddy-network
      - default

  api:
    restart: unless-stopped
    build: ./backend
    env_file: .env.backend
    networks:
      - caddy-network
      - default

networks:
  caddy-network:
    external: true
