version: '3.8'

volumes:
    db:
    minio:

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
