openapi: 3.0.3
info:
  title: Wargame Service
  description: HTTP service for the SSM Wargame
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for wargame
paths:
  /challenge:
    get:
      tags:
      - challenge
      summary: ListChallenges challenge
      operationId: challenge#ListChallenges
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SsmChallengeResponseCollection'
              example:
              - description: A simple memory exploit bla bla
                files:
                - {}
                - {}
                - {}
                id: uuid
                published: true
                score: 50
                services:
                - {}
                - {}
                title: pwnme bla bla
              - description: A simple memory exploit bla bla
                files:
                - {}
                - {}
                - {}
                id: uuid
                published: true
                score: 50
                services:
                - {}
                - {}
                title: pwnme bla bla
              - description: A simple memory exploit bla bla
                files:
                - {}
                - {}
                - {}
                id: uuid
                published: true
                score: 50
                services:
                - {}
                - {}
                title: pwnme bla bla
components:
  schemas:
    ChallengeService:
      type: object
      example: {}
    SsmChallengeResponse:
      type: object
      properties:
        description:
          type: string
          example: A simple memory exploit bla bla
        files:
          type: array
          items:
            $ref: '#/components/schemas/ChallengeService'
          example:
          - {}
          - {}
          - {}
        id:
          type: string
          example: uuid
        published:
          type: boolean
          example: true
        score:
          type: integer
          example: 50
          minimum: 0
        services:
          type: array
          items:
            $ref: '#/components/schemas/ChallengeService'
          example:
          - {}
          - {}
        title:
          type: string
          example: pwnme bla bla
      description: A Wargame challenge (default view)
      example:
        description: A simple memory exploit bla bla
        files:
        - {}
        - {}
        id: uuid
        published: true
        score: 50
        services:
        - {}
        - {}
        title: pwnme bla bla
      required:
      - id
      - title
      - description
      - score
      - published
    SsmChallengeResponseCollection:
      type: array
      items:
        $ref: '#/components/schemas/SsmChallengeResponse'
      description: ListChallengesResponseBody is the result type for an array of SsmChallengeResponse
        (default view)
      example:
      - description: A simple memory exploit bla bla
        files:
        - {}
        - {}
        - {}
        id: uuid
        published: true
        score: 50
        services:
        - {}
        - {}
        title: pwnme bla bla
      - description: A simple memory exploit bla bla
        files:
        - {}
        - {}
        - {}
        id: uuid
        published: true
        score: 50
        services:
        - {}
        - {}
        title: pwnme bla bla
tags:
- name: challenge
