// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Authors                  string
	Categories               string
	ChallengeAuthors         string
	ChallengeFiles           string
	ChallengeGroupChallenges string
	ChallengeGroups          string
	ChallengeServices        string
	Challenges               string
	ChalltoolsImportToken    string
	CourseAuthors            string
	CourseEnrollments        string
	CourseItems              string
	Courses                  string
	CTFChallenges            string
	CTFEvents                string
	CTFSolves                string
	CTFTeams                 string
	CTFUsers                 string
	CTFS                     string
	Flags                    string
	KnackKodenSolves         string
	KnackKodenTeams          string
	MonthlyChallenges        string
	SchoolSolves             string
	Schools                  string
	Submissions              string
	UserSolves               string
	Users                    string
}{
	Authors:                  "authors",
	Categories:               "categories",
	ChallengeAuthors:         "challenge_authors",
	ChallengeFiles:           "challenge_files",
	ChallengeGroupChallenges: "challenge_group_challenges",
	ChallengeGroups:          "challenge_groups",
	ChallengeServices:        "challenge_services",
	Challenges:               "challenges",
	ChalltoolsImportToken:    "challtools_import_token",
	CourseAuthors:            "course_authors",
	CourseEnrollments:        "course_enrollments",
	CourseItems:              "course_items",
	Courses:                  "courses",
	CTFChallenges:            "ctf_challenges",
	CTFEvents:                "ctf_events",
	CTFSolves:                "ctf_solves",
	CTFTeams:                 "ctf_teams",
	CTFUsers:                 "ctf_users",
	CTFS:                     "ctfs",
	Flags:                    "flags",
	KnackKodenSolves:         "knack_koden_solves",
	KnackKodenTeams:          "knack_koden_teams",
	MonthlyChallenges:        "monthly_challenges",
	SchoolSolves:             "school_solves",
	Schools:                  "schools",
	Submissions:              "submissions",
	UserSolves:               "user_solves",
	Users:                    "users",
}
