// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ChallengeGroup is an object representing the database table.
type ChallengeGroup struct {
	ID          string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name        string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description string    `boil:"description" json:"description" toml:"description" yaml:"description"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *challengeGroupR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L challengeGroupL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ChallengeGroupColumns = struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "id",
	Name:        "name",
	Description: "description",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var ChallengeGroupTableColumns = struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "challenge_groups.id",
	Name:        "challenge_groups.name",
	Description: "challenge_groups.description",
	CreatedAt:   "challenge_groups.created_at",
	UpdatedAt:   "challenge_groups.updated_at",
}

// Generated where

var ChallengeGroupWhere = struct {
	ID          whereHelperstring
	Name        whereHelperstring
	Description whereHelperstring
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
}{
	ID:          whereHelperstring{field: "\"challenge_groups\".\"id\""},
	Name:        whereHelperstring{field: "\"challenge_groups\".\"name\""},
	Description: whereHelperstring{field: "\"challenge_groups\".\"description\""},
	CreatedAt:   whereHelpertime_Time{field: "\"challenge_groups\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"challenge_groups\".\"updated_at\""},
}

// ChallengeGroupRels is where relationship names are stored.
var ChallengeGroupRels = struct {
	ChallengeGroupChallenges string
}{
	ChallengeGroupChallenges: "ChallengeGroupChallenges",
}

// challengeGroupR is where relationships are stored.
type challengeGroupR struct {
	ChallengeGroupChallenges ChallengeGroupChallengeSlice `boil:"ChallengeGroupChallenges" json:"ChallengeGroupChallenges" toml:"ChallengeGroupChallenges" yaml:"ChallengeGroupChallenges"`
}

// NewStruct creates a new relationship struct
func (*challengeGroupR) NewStruct() *challengeGroupR {
	return &challengeGroupR{}
}

func (r *challengeGroupR) GetChallengeGroupChallenges() ChallengeGroupChallengeSlice {
	if r == nil {
		return nil
	}
	return r.ChallengeGroupChallenges
}

// challengeGroupL is where Load methods for each relationship are stored.
type challengeGroupL struct{}

var (
	challengeGroupAllColumns            = []string{"id", "name", "description", "created_at", "updated_at"}
	challengeGroupColumnsWithoutDefault = []string{"id", "name", "description"}
	challengeGroupColumnsWithDefault    = []string{"created_at", "updated_at"}
	challengeGroupPrimaryKeyColumns     = []string{"id"}
	challengeGroupGeneratedColumns      = []string{}
)

type (
	// ChallengeGroupSlice is an alias for a slice of pointers to ChallengeGroup.
	// This should almost always be used instead of []ChallengeGroup.
	ChallengeGroupSlice []*ChallengeGroup
	// ChallengeGroupHook is the signature for custom ChallengeGroup hook methods
	ChallengeGroupHook func(context.Context, boil.ContextExecutor, *ChallengeGroup) error

	challengeGroupQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	challengeGroupType                 = reflect.TypeOf(&ChallengeGroup{})
	challengeGroupMapping              = queries.MakeStructMapping(challengeGroupType)
	challengeGroupPrimaryKeyMapping, _ = queries.BindMapping(challengeGroupType, challengeGroupMapping, challengeGroupPrimaryKeyColumns)
	challengeGroupInsertCacheMut       sync.RWMutex
	challengeGroupInsertCache          = make(map[string]insertCache)
	challengeGroupUpdateCacheMut       sync.RWMutex
	challengeGroupUpdateCache          = make(map[string]updateCache)
	challengeGroupUpsertCacheMut       sync.RWMutex
	challengeGroupUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var challengeGroupAfterSelectHooks []ChallengeGroupHook

var challengeGroupBeforeInsertHooks []ChallengeGroupHook
var challengeGroupAfterInsertHooks []ChallengeGroupHook

var challengeGroupBeforeUpdateHooks []ChallengeGroupHook
var challengeGroupAfterUpdateHooks []ChallengeGroupHook

var challengeGroupBeforeDeleteHooks []ChallengeGroupHook
var challengeGroupAfterDeleteHooks []ChallengeGroupHook

var challengeGroupBeforeUpsertHooks []ChallengeGroupHook
var challengeGroupAfterUpsertHooks []ChallengeGroupHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ChallengeGroup) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ChallengeGroup) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ChallengeGroup) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ChallengeGroup) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ChallengeGroup) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ChallengeGroup) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ChallengeGroup) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ChallengeGroup) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ChallengeGroup) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddChallengeGroupHook registers your hook function for all future operations.
func AddChallengeGroupHook(hookPoint boil.HookPoint, challengeGroupHook ChallengeGroupHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		challengeGroupAfterSelectHooks = append(challengeGroupAfterSelectHooks, challengeGroupHook)
	case boil.BeforeInsertHook:
		challengeGroupBeforeInsertHooks = append(challengeGroupBeforeInsertHooks, challengeGroupHook)
	case boil.AfterInsertHook:
		challengeGroupAfterInsertHooks = append(challengeGroupAfterInsertHooks, challengeGroupHook)
	case boil.BeforeUpdateHook:
		challengeGroupBeforeUpdateHooks = append(challengeGroupBeforeUpdateHooks, challengeGroupHook)
	case boil.AfterUpdateHook:
		challengeGroupAfterUpdateHooks = append(challengeGroupAfterUpdateHooks, challengeGroupHook)
	case boil.BeforeDeleteHook:
		challengeGroupBeforeDeleteHooks = append(challengeGroupBeforeDeleteHooks, challengeGroupHook)
	case boil.AfterDeleteHook:
		challengeGroupAfterDeleteHooks = append(challengeGroupAfterDeleteHooks, challengeGroupHook)
	case boil.BeforeUpsertHook:
		challengeGroupBeforeUpsertHooks = append(challengeGroupBeforeUpsertHooks, challengeGroupHook)
	case boil.AfterUpsertHook:
		challengeGroupAfterUpsertHooks = append(challengeGroupAfterUpsertHooks, challengeGroupHook)
	}
}

// One returns a single challengeGroup record from the query.
func (q challengeGroupQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ChallengeGroup, error) {
	o := &ChallengeGroup{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for challenge_groups")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ChallengeGroup records from the query.
func (q challengeGroupQuery) All(ctx context.Context, exec boil.ContextExecutor) (ChallengeGroupSlice, error) {
	var o []*ChallengeGroup

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ChallengeGroup slice")
	}

	if len(challengeGroupAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ChallengeGroup records in the query.
func (q challengeGroupQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count challenge_groups rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q challengeGroupQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if challenge_groups exists")
	}

	return count > 0, nil
}

// ChallengeGroupChallenges retrieves all the challenge_group_challenge's ChallengeGroupChallenges with an executor.
func (o *ChallengeGroup) ChallengeGroupChallenges(mods ...qm.QueryMod) challengeGroupChallengeQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"challenge_group_challenges\".\"challenge_group_id\"=?", o.ID),
	)

	return ChallengeGroupChallenges(queryMods...)
}

// LoadChallengeGroupChallenges allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (challengeGroupL) LoadChallengeGroupChallenges(ctx context.Context, e boil.ContextExecutor, singular bool, maybeChallengeGroup interface{}, mods queries.Applicator) error {
	var slice []*ChallengeGroup
	var object *ChallengeGroup

	if singular {
		var ok bool
		object, ok = maybeChallengeGroup.(*ChallengeGroup)
		if !ok {
			object = new(ChallengeGroup)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeChallengeGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeChallengeGroup))
			}
		}
	} else {
		s, ok := maybeChallengeGroup.(*[]*ChallengeGroup)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeChallengeGroup)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeChallengeGroup))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &challengeGroupR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &challengeGroupR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`challenge_group_challenges`),
		qm.WhereIn(`challenge_group_challenges.challenge_group_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load challenge_group_challenges")
	}

	var resultSlice []*ChallengeGroupChallenge
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice challenge_group_challenges")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on challenge_group_challenges")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for challenge_group_challenges")
	}

	if len(challengeGroupChallengeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.ChallengeGroupChallenges = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &challengeGroupChallengeR{}
			}
			foreign.R.ChallengeGroup = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.ChallengeGroupID {
				local.R.ChallengeGroupChallenges = append(local.R.ChallengeGroupChallenges, foreign)
				if foreign.R == nil {
					foreign.R = &challengeGroupChallengeR{}
				}
				foreign.R.ChallengeGroup = local
				break
			}
		}
	}

	return nil
}

// AddChallengeGroupChallenges adds the given related objects to the existing relationships
// of the challenge_group, optionally inserting them as new records.
// Appends related to o.R.ChallengeGroupChallenges.
// Sets related.R.ChallengeGroup appropriately.
func (o *ChallengeGroup) AddChallengeGroupChallenges(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ChallengeGroupChallenge) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ChallengeGroupID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"challenge_group_challenges\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"challenge_group_id"}),
				strmangle.WhereClause("\"", "\"", 2, challengeGroupChallengePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ChallengeGroupID, rel.ChallengeID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ChallengeGroupID = o.ID
		}
	}

	if o.R == nil {
		o.R = &challengeGroupR{
			ChallengeGroupChallenges: related,
		}
	} else {
		o.R.ChallengeGroupChallenges = append(o.R.ChallengeGroupChallenges, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &challengeGroupChallengeR{
				ChallengeGroup: o,
			}
		} else {
			rel.R.ChallengeGroup = o
		}
	}
	return nil
}

// ChallengeGroups retrieves all the records using an executor.
func ChallengeGroups(mods ...qm.QueryMod) challengeGroupQuery {
	mods = append(mods, qm.From("\"challenge_groups\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"challenge_groups\".*"})
	}

	return challengeGroupQuery{q}
}

// FindChallengeGroup retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindChallengeGroup(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ChallengeGroup, error) {
	challengeGroupObj := &ChallengeGroup{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"challenge_groups\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, challengeGroupObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from challenge_groups")
	}

	if err = challengeGroupObj.doAfterSelectHooks(ctx, exec); err != nil {
		return challengeGroupObj, err
	}

	return challengeGroupObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ChallengeGroup) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no challenge_groups provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(challengeGroupColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	challengeGroupInsertCacheMut.RLock()
	cache, cached := challengeGroupInsertCache[key]
	challengeGroupInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			challengeGroupAllColumns,
			challengeGroupColumnsWithDefault,
			challengeGroupColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(challengeGroupType, challengeGroupMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(challengeGroupType, challengeGroupMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"challenge_groups\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"challenge_groups\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into challenge_groups")
	}

	if !cached {
		challengeGroupInsertCacheMut.Lock()
		challengeGroupInsertCache[key] = cache
		challengeGroupInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ChallengeGroup.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ChallengeGroup) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	challengeGroupUpdateCacheMut.RLock()
	cache, cached := challengeGroupUpdateCache[key]
	challengeGroupUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			challengeGroupAllColumns,
			challengeGroupPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update challenge_groups, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"challenge_groups\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, challengeGroupPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(challengeGroupType, challengeGroupMapping, append(wl, challengeGroupPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update challenge_groups row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for challenge_groups")
	}

	if !cached {
		challengeGroupUpdateCacheMut.Lock()
		challengeGroupUpdateCache[key] = cache
		challengeGroupUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q challengeGroupQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for challenge_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for challenge_groups")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ChallengeGroupSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), challengeGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"challenge_groups\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, challengeGroupPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in challengeGroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all challengeGroup")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ChallengeGroup) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no challenge_groups provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(challengeGroupColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	challengeGroupUpsertCacheMut.RLock()
	cache, cached := challengeGroupUpsertCache[key]
	challengeGroupUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			challengeGroupAllColumns,
			challengeGroupColumnsWithDefault,
			challengeGroupColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			challengeGroupAllColumns,
			challengeGroupPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert challenge_groups, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(challengeGroupPrimaryKeyColumns))
			copy(conflict, challengeGroupPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"challenge_groups\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(challengeGroupType, challengeGroupMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(challengeGroupType, challengeGroupMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert challenge_groups")
	}

	if !cached {
		challengeGroupUpsertCacheMut.Lock()
		challengeGroupUpsertCache[key] = cache
		challengeGroupUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ChallengeGroup record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ChallengeGroup) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ChallengeGroup provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), challengeGroupPrimaryKeyMapping)
	sql := "DELETE FROM \"challenge_groups\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from challenge_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for challenge_groups")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q challengeGroupQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no challengeGroupQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from challenge_groups")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for challenge_groups")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ChallengeGroupSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(challengeGroupBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), challengeGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"challenge_groups\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, challengeGroupPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from challengeGroup slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for challenge_groups")
	}

	if len(challengeGroupAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ChallengeGroup) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindChallengeGroup(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ChallengeGroupSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ChallengeGroupSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), challengeGroupPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"challenge_groups\".* FROM \"challenge_groups\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, challengeGroupPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ChallengeGroupSlice")
	}

	*o = slice

	return nil
}

// ChallengeGroupExists checks if the ChallengeGroup row exists.
func ChallengeGroupExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"challenge_groups\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if challenge_groups exists")
	}

	return exists, nil
}

// Exists checks if the ChallengeGroup row exists.
func (o *ChallengeGroup) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ChallengeGroupExists(ctx, exec, o.ID)
}
