// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ChallengeGroupChallenge is an object representing the database table.
type ChallengeGroupChallenge struct {
	ChallengeGroupID string   `boil:"challenge_group_id" json:"challenge_group_id" toml:"challenge_group_id" yaml:"challenge_group_id"`
	ChallengeID      string   `boil:"challenge_id" json:"challenge_id" toml:"challenge_id" yaml:"challenge_id"`
	CustomScore      null.Int `boil:"custom_score" json:"custom_score,omitempty" toml:"custom_score" yaml:"custom_score,omitempty"`
	DisplayOrder     int      `boil:"display_order" json:"display_order" toml:"display_order" yaml:"display_order"`

	R *challengeGroupChallengeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L challengeGroupChallengeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ChallengeGroupChallengeColumns = struct {
	ChallengeGroupID string
	ChallengeID      string
	CustomScore      string
	DisplayOrder     string
}{
	ChallengeGroupID: "challenge_group_id",
	ChallengeID:      "challenge_id",
	CustomScore:      "custom_score",
	DisplayOrder:     "display_order",
}

var ChallengeGroupChallengeTableColumns = struct {
	ChallengeGroupID string
	ChallengeID      string
	CustomScore      string
	DisplayOrder     string
}{
	ChallengeGroupID: "challenge_group_challenges.challenge_group_id",
	ChallengeID:      "challenge_group_challenges.challenge_id",
	CustomScore:      "challenge_group_challenges.custom_score",
	DisplayOrder:     "challenge_group_challenges.display_order",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var ChallengeGroupChallengeWhere = struct {
	ChallengeGroupID whereHelperstring
	ChallengeID      whereHelperstring
	CustomScore      whereHelpernull_Int
	DisplayOrder     whereHelperint
}{
	ChallengeGroupID: whereHelperstring{field: "\"challenge_group_challenges\".\"challenge_group_id\""},
	ChallengeID:      whereHelperstring{field: "\"challenge_group_challenges\".\"challenge_id\""},
	CustomScore:      whereHelpernull_Int{field: "\"challenge_group_challenges\".\"custom_score\""},
	DisplayOrder:     whereHelperint{field: "\"challenge_group_challenges\".\"display_order\""},
}

// ChallengeGroupChallengeRels is where relationship names are stored.
var ChallengeGroupChallengeRels = struct {
	ChallengeGroup string
	Challenge      string
}{
	ChallengeGroup: "ChallengeGroup",
	Challenge:      "Challenge",
}

// challengeGroupChallengeR is where relationships are stored.
type challengeGroupChallengeR struct {
	ChallengeGroup *ChallengeGroup `boil:"ChallengeGroup" json:"ChallengeGroup" toml:"ChallengeGroup" yaml:"ChallengeGroup"`
	Challenge      *Challenge      `boil:"Challenge" json:"Challenge" toml:"Challenge" yaml:"Challenge"`
}

// NewStruct creates a new relationship struct
func (*challengeGroupChallengeR) NewStruct() *challengeGroupChallengeR {
	return &challengeGroupChallengeR{}
}

func (r *challengeGroupChallengeR) GetChallengeGroup() *ChallengeGroup {
	if r == nil {
		return nil
	}
	return r.ChallengeGroup
}

func (r *challengeGroupChallengeR) GetChallenge() *Challenge {
	if r == nil {
		return nil
	}
	return r.Challenge
}

// challengeGroupChallengeL is where Load methods for each relationship are stored.
type challengeGroupChallengeL struct{}

var (
	challengeGroupChallengeAllColumns            = []string{"challenge_group_id", "challenge_id", "custom_score", "display_order"}
	challengeGroupChallengeColumnsWithoutDefault = []string{"challenge_group_id", "challenge_id", "display_order"}
	challengeGroupChallengeColumnsWithDefault    = []string{"custom_score"}
	challengeGroupChallengePrimaryKeyColumns     = []string{"challenge_group_id", "challenge_id"}
	challengeGroupChallengeGeneratedColumns      = []string{}
)

type (
	// ChallengeGroupChallengeSlice is an alias for a slice of pointers to ChallengeGroupChallenge.
	// This should almost always be used instead of []ChallengeGroupChallenge.
	ChallengeGroupChallengeSlice []*ChallengeGroupChallenge
	// ChallengeGroupChallengeHook is the signature for custom ChallengeGroupChallenge hook methods
	ChallengeGroupChallengeHook func(context.Context, boil.ContextExecutor, *ChallengeGroupChallenge) error

	challengeGroupChallengeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	challengeGroupChallengeType                 = reflect.TypeOf(&ChallengeGroupChallenge{})
	challengeGroupChallengeMapping              = queries.MakeStructMapping(challengeGroupChallengeType)
	challengeGroupChallengePrimaryKeyMapping, _ = queries.BindMapping(challengeGroupChallengeType, challengeGroupChallengeMapping, challengeGroupChallengePrimaryKeyColumns)
	challengeGroupChallengeInsertCacheMut       sync.RWMutex
	challengeGroupChallengeInsertCache          = make(map[string]insertCache)
	challengeGroupChallengeUpdateCacheMut       sync.RWMutex
	challengeGroupChallengeUpdateCache          = make(map[string]updateCache)
	challengeGroupChallengeUpsertCacheMut       sync.RWMutex
	challengeGroupChallengeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var challengeGroupChallengeAfterSelectHooks []ChallengeGroupChallengeHook

var challengeGroupChallengeBeforeInsertHooks []ChallengeGroupChallengeHook
var challengeGroupChallengeAfterInsertHooks []ChallengeGroupChallengeHook

var challengeGroupChallengeBeforeUpdateHooks []ChallengeGroupChallengeHook
var challengeGroupChallengeAfterUpdateHooks []ChallengeGroupChallengeHook

var challengeGroupChallengeBeforeDeleteHooks []ChallengeGroupChallengeHook
var challengeGroupChallengeAfterDeleteHooks []ChallengeGroupChallengeHook

var challengeGroupChallengeBeforeUpsertHooks []ChallengeGroupChallengeHook
var challengeGroupChallengeAfterUpsertHooks []ChallengeGroupChallengeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ChallengeGroupChallenge) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupChallengeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ChallengeGroupChallenge) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupChallengeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ChallengeGroupChallenge) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupChallengeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ChallengeGroupChallenge) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupChallengeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ChallengeGroupChallenge) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupChallengeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ChallengeGroupChallenge) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupChallengeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ChallengeGroupChallenge) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupChallengeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ChallengeGroupChallenge) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupChallengeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ChallengeGroupChallenge) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range challengeGroupChallengeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddChallengeGroupChallengeHook registers your hook function for all future operations.
func AddChallengeGroupChallengeHook(hookPoint boil.HookPoint, challengeGroupChallengeHook ChallengeGroupChallengeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		challengeGroupChallengeAfterSelectHooks = append(challengeGroupChallengeAfterSelectHooks, challengeGroupChallengeHook)
	case boil.BeforeInsertHook:
		challengeGroupChallengeBeforeInsertHooks = append(challengeGroupChallengeBeforeInsertHooks, challengeGroupChallengeHook)
	case boil.AfterInsertHook:
		challengeGroupChallengeAfterInsertHooks = append(challengeGroupChallengeAfterInsertHooks, challengeGroupChallengeHook)
	case boil.BeforeUpdateHook:
		challengeGroupChallengeBeforeUpdateHooks = append(challengeGroupChallengeBeforeUpdateHooks, challengeGroupChallengeHook)
	case boil.AfterUpdateHook:
		challengeGroupChallengeAfterUpdateHooks = append(challengeGroupChallengeAfterUpdateHooks, challengeGroupChallengeHook)
	case boil.BeforeDeleteHook:
		challengeGroupChallengeBeforeDeleteHooks = append(challengeGroupChallengeBeforeDeleteHooks, challengeGroupChallengeHook)
	case boil.AfterDeleteHook:
		challengeGroupChallengeAfterDeleteHooks = append(challengeGroupChallengeAfterDeleteHooks, challengeGroupChallengeHook)
	case boil.BeforeUpsertHook:
		challengeGroupChallengeBeforeUpsertHooks = append(challengeGroupChallengeBeforeUpsertHooks, challengeGroupChallengeHook)
	case boil.AfterUpsertHook:
		challengeGroupChallengeAfterUpsertHooks = append(challengeGroupChallengeAfterUpsertHooks, challengeGroupChallengeHook)
	}
}

// One returns a single challengeGroupChallenge record from the query.
func (q challengeGroupChallengeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ChallengeGroupChallenge, error) {
	o := &ChallengeGroupChallenge{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for challenge_group_challenges")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ChallengeGroupChallenge records from the query.
func (q challengeGroupChallengeQuery) All(ctx context.Context, exec boil.ContextExecutor) (ChallengeGroupChallengeSlice, error) {
	var o []*ChallengeGroupChallenge

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ChallengeGroupChallenge slice")
	}

	if len(challengeGroupChallengeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ChallengeGroupChallenge records in the query.
func (q challengeGroupChallengeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count challenge_group_challenges rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q challengeGroupChallengeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if challenge_group_challenges exists")
	}

	return count > 0, nil
}

// ChallengeGroup pointed to by the foreign key.
func (o *ChallengeGroupChallenge) ChallengeGroup(mods ...qm.QueryMod) challengeGroupQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChallengeGroupID),
	}

	queryMods = append(queryMods, mods...)

	return ChallengeGroups(queryMods...)
}

// Challenge pointed to by the foreign key.
func (o *ChallengeGroupChallenge) Challenge(mods ...qm.QueryMod) challengeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChallengeID),
	}

	queryMods = append(queryMods, mods...)

	return Challenges(queryMods...)
}

// LoadChallengeGroup allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (challengeGroupChallengeL) LoadChallengeGroup(ctx context.Context, e boil.ContextExecutor, singular bool, maybeChallengeGroupChallenge interface{}, mods queries.Applicator) error {
	var slice []*ChallengeGroupChallenge
	var object *ChallengeGroupChallenge

	if singular {
		var ok bool
		object, ok = maybeChallengeGroupChallenge.(*ChallengeGroupChallenge)
		if !ok {
			object = new(ChallengeGroupChallenge)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeChallengeGroupChallenge)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeChallengeGroupChallenge))
			}
		}
	} else {
		s, ok := maybeChallengeGroupChallenge.(*[]*ChallengeGroupChallenge)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeChallengeGroupChallenge)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeChallengeGroupChallenge))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &challengeGroupChallengeR{}
		}
		args = append(args, object.ChallengeGroupID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &challengeGroupChallengeR{}
			}

			for _, a := range args {
				if a == obj.ChallengeGroupID {
					continue Outer
				}
			}

			args = append(args, obj.ChallengeGroupID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`challenge_groups`),
		qm.WhereIn(`challenge_groups.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ChallengeGroup")
	}

	var resultSlice []*ChallengeGroup
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ChallengeGroup")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for challenge_groups")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for challenge_groups")
	}

	if len(challengeGroupAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ChallengeGroup = foreign
		if foreign.R == nil {
			foreign.R = &challengeGroupR{}
		}
		foreign.R.ChallengeGroupChallenges = append(foreign.R.ChallengeGroupChallenges, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ChallengeGroupID == foreign.ID {
				local.R.ChallengeGroup = foreign
				if foreign.R == nil {
					foreign.R = &challengeGroupR{}
				}
				foreign.R.ChallengeGroupChallenges = append(foreign.R.ChallengeGroupChallenges, local)
				break
			}
		}
	}

	return nil
}

// LoadChallenge allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (challengeGroupChallengeL) LoadChallenge(ctx context.Context, e boil.ContextExecutor, singular bool, maybeChallengeGroupChallenge interface{}, mods queries.Applicator) error {
	var slice []*ChallengeGroupChallenge
	var object *ChallengeGroupChallenge

	if singular {
		var ok bool
		object, ok = maybeChallengeGroupChallenge.(*ChallengeGroupChallenge)
		if !ok {
			object = new(ChallengeGroupChallenge)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeChallengeGroupChallenge)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeChallengeGroupChallenge))
			}
		}
	} else {
		s, ok := maybeChallengeGroupChallenge.(*[]*ChallengeGroupChallenge)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeChallengeGroupChallenge)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeChallengeGroupChallenge))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &challengeGroupChallengeR{}
		}
		args = append(args, object.ChallengeID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &challengeGroupChallengeR{}
			}

			for _, a := range args {
				if a == obj.ChallengeID {
					continue Outer
				}
			}

			args = append(args, obj.ChallengeID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`challenges`),
		qm.WhereIn(`challenges.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Challenge")
	}

	var resultSlice []*Challenge
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Challenge")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for challenges")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for challenges")
	}

	if len(challengeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Challenge = foreign
		if foreign.R == nil {
			foreign.R = &challengeR{}
		}
		foreign.R.ChallengeGroupChallenges = append(foreign.R.ChallengeGroupChallenges, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ChallengeID == foreign.ID {
				local.R.Challenge = foreign
				if foreign.R == nil {
					foreign.R = &challengeR{}
				}
				foreign.R.ChallengeGroupChallenges = append(foreign.R.ChallengeGroupChallenges, local)
				break
			}
		}
	}

	return nil
}

// SetChallengeGroup of the challengeGroupChallenge to the related item.
// Sets o.R.ChallengeGroup to related.
// Adds o to related.R.ChallengeGroupChallenges.
func (o *ChallengeGroupChallenge) SetChallengeGroup(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ChallengeGroup) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"challenge_group_challenges\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"challenge_group_id"}),
		strmangle.WhereClause("\"", "\"", 2, challengeGroupChallengePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ChallengeGroupID, o.ChallengeID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ChallengeGroupID = related.ID
	if o.R == nil {
		o.R = &challengeGroupChallengeR{
			ChallengeGroup: related,
		}
	} else {
		o.R.ChallengeGroup = related
	}

	if related.R == nil {
		related.R = &challengeGroupR{
			ChallengeGroupChallenges: ChallengeGroupChallengeSlice{o},
		}
	} else {
		related.R.ChallengeGroupChallenges = append(related.R.ChallengeGroupChallenges, o)
	}

	return nil
}

// SetChallenge of the challengeGroupChallenge to the related item.
// Sets o.R.Challenge to related.
// Adds o to related.R.ChallengeGroupChallenges.
func (o *ChallengeGroupChallenge) SetChallenge(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Challenge) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"challenge_group_challenges\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"challenge_id"}),
		strmangle.WhereClause("\"", "\"", 2, challengeGroupChallengePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ChallengeGroupID, o.ChallengeID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ChallengeID = related.ID
	if o.R == nil {
		o.R = &challengeGroupChallengeR{
			Challenge: related,
		}
	} else {
		o.R.Challenge = related
	}

	if related.R == nil {
		related.R = &challengeR{
			ChallengeGroupChallenges: ChallengeGroupChallengeSlice{o},
		}
	} else {
		related.R.ChallengeGroupChallenges = append(related.R.ChallengeGroupChallenges, o)
	}

	return nil
}

// ChallengeGroupChallenges retrieves all the records using an executor.
func ChallengeGroupChallenges(mods ...qm.QueryMod) challengeGroupChallengeQuery {
	mods = append(mods, qm.From("\"challenge_group_challenges\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"challenge_group_challenges\".*"})
	}

	return challengeGroupChallengeQuery{q}
}

// FindChallengeGroupChallenge retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindChallengeGroupChallenge(ctx context.Context, exec boil.ContextExecutor, challengeGroupID string, challengeID string, selectCols ...string) (*ChallengeGroupChallenge, error) {
	challengeGroupChallengeObj := &ChallengeGroupChallenge{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"challenge_group_challenges\" where \"challenge_group_id\"=$1 AND \"challenge_id\"=$2", sel,
	)

	q := queries.Raw(query, challengeGroupID, challengeID)

	err := q.Bind(ctx, exec, challengeGroupChallengeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from challenge_group_challenges")
	}

	if err = challengeGroupChallengeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return challengeGroupChallengeObj, err
	}

	return challengeGroupChallengeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ChallengeGroupChallenge) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no challenge_group_challenges provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(challengeGroupChallengeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	challengeGroupChallengeInsertCacheMut.RLock()
	cache, cached := challengeGroupChallengeInsertCache[key]
	challengeGroupChallengeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			challengeGroupChallengeAllColumns,
			challengeGroupChallengeColumnsWithDefault,
			challengeGroupChallengeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(challengeGroupChallengeType, challengeGroupChallengeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(challengeGroupChallengeType, challengeGroupChallengeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"challenge_group_challenges\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"challenge_group_challenges\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into challenge_group_challenges")
	}

	if !cached {
		challengeGroupChallengeInsertCacheMut.Lock()
		challengeGroupChallengeInsertCache[key] = cache
		challengeGroupChallengeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ChallengeGroupChallenge.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ChallengeGroupChallenge) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	challengeGroupChallengeUpdateCacheMut.RLock()
	cache, cached := challengeGroupChallengeUpdateCache[key]
	challengeGroupChallengeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			challengeGroupChallengeAllColumns,
			challengeGroupChallengePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update challenge_group_challenges, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"challenge_group_challenges\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, challengeGroupChallengePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(challengeGroupChallengeType, challengeGroupChallengeMapping, append(wl, challengeGroupChallengePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update challenge_group_challenges row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for challenge_group_challenges")
	}

	if !cached {
		challengeGroupChallengeUpdateCacheMut.Lock()
		challengeGroupChallengeUpdateCache[key] = cache
		challengeGroupChallengeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q challengeGroupChallengeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for challenge_group_challenges")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for challenge_group_challenges")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ChallengeGroupChallengeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), challengeGroupChallengePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"challenge_group_challenges\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, challengeGroupChallengePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in challengeGroupChallenge slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all challengeGroupChallenge")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ChallengeGroupChallenge) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no challenge_group_challenges provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(challengeGroupChallengeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	challengeGroupChallengeUpsertCacheMut.RLock()
	cache, cached := challengeGroupChallengeUpsertCache[key]
	challengeGroupChallengeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			challengeGroupChallengeAllColumns,
			challengeGroupChallengeColumnsWithDefault,
			challengeGroupChallengeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			challengeGroupChallengeAllColumns,
			challengeGroupChallengePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert challenge_group_challenges, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(challengeGroupChallengePrimaryKeyColumns))
			copy(conflict, challengeGroupChallengePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"challenge_group_challenges\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(challengeGroupChallengeType, challengeGroupChallengeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(challengeGroupChallengeType, challengeGroupChallengeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert challenge_group_challenges")
	}

	if !cached {
		challengeGroupChallengeUpsertCacheMut.Lock()
		challengeGroupChallengeUpsertCache[key] = cache
		challengeGroupChallengeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ChallengeGroupChallenge record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ChallengeGroupChallenge) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ChallengeGroupChallenge provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), challengeGroupChallengePrimaryKeyMapping)
	sql := "DELETE FROM \"challenge_group_challenges\" WHERE \"challenge_group_id\"=$1 AND \"challenge_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from challenge_group_challenges")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for challenge_group_challenges")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q challengeGroupChallengeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no challengeGroupChallengeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from challenge_group_challenges")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for challenge_group_challenges")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ChallengeGroupChallengeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(challengeGroupChallengeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), challengeGroupChallengePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"challenge_group_challenges\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, challengeGroupChallengePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from challengeGroupChallenge slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for challenge_group_challenges")
	}

	if len(challengeGroupChallengeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ChallengeGroupChallenge) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindChallengeGroupChallenge(ctx, exec, o.ChallengeGroupID, o.ChallengeID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ChallengeGroupChallengeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ChallengeGroupChallengeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), challengeGroupChallengePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"challenge_group_challenges\".* FROM \"challenge_group_challenges\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, challengeGroupChallengePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ChallengeGroupChallengeSlice")
	}

	*o = slice

	return nil
}

// ChallengeGroupChallengeExists checks if the ChallengeGroupChallenge row exists.
func ChallengeGroupChallengeExists(ctx context.Context, exec boil.ContextExecutor, challengeGroupID string, challengeID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"challenge_group_challenges\" where \"challenge_group_id\"=$1 AND \"challenge_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, challengeGroupID, challengeID)
	}
	row := exec.QueryRowContext(ctx, sql, challengeGroupID, challengeID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if challenge_group_challenges exists")
	}

	return exists, nil
}

// Exists checks if the ChallengeGroupChallenge row exists.
func (o *ChallengeGroupChallenge) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ChallengeGroupChallengeExists(ctx, exec, o.ChallengeGroupID, o.ChallengeID)
}
