// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// CourseEnrollment is an object representing the database table.
type CourseEnrollment struct {
	ID         string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	CourseID   string    `boil:"course_id" json:"course_id" toml:"course_id" yaml:"course_id"`
	UserID     string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	FinishedAt null.Time `boil:"finished_at" json:"finished_at,omitempty" toml:"finished_at" yaml:"finished_at,omitempty"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	Finished   bool      `boil:"finished" json:"finished" toml:"finished" yaml:"finished"`

	R *courseEnrollmentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L courseEnrollmentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CourseEnrollmentColumns = struct {
	ID         string
	CourseID   string
	UserID     string
	FinishedAt string
	CreatedAt  string
	Finished   string
}{
	ID:         "id",
	CourseID:   "course_id",
	UserID:     "user_id",
	FinishedAt: "finished_at",
	CreatedAt:  "created_at",
	Finished:   "finished",
}

var CourseEnrollmentTableColumns = struct {
	ID         string
	CourseID   string
	UserID     string
	FinishedAt string
	CreatedAt  string
	Finished   string
}{
	ID:         "course_enrollments.id",
	CourseID:   "course_enrollments.course_id",
	UserID:     "course_enrollments.user_id",
	FinishedAt: "course_enrollments.finished_at",
	CreatedAt:  "course_enrollments.created_at",
	Finished:   "course_enrollments.finished",
}

// Generated where

var CourseEnrollmentWhere = struct {
	ID         whereHelperstring
	CourseID   whereHelperstring
	UserID     whereHelperstring
	FinishedAt whereHelpernull_Time
	CreatedAt  whereHelpertime_Time
	Finished   whereHelperbool
}{
	ID:         whereHelperstring{field: "\"course_enrollments\".\"id\""},
	CourseID:   whereHelperstring{field: "\"course_enrollments\".\"course_id\""},
	UserID:     whereHelperstring{field: "\"course_enrollments\".\"user_id\""},
	FinishedAt: whereHelpernull_Time{field: "\"course_enrollments\".\"finished_at\""},
	CreatedAt:  whereHelpertime_Time{field: "\"course_enrollments\".\"created_at\""},
	Finished:   whereHelperbool{field: "\"course_enrollments\".\"finished\""},
}

// CourseEnrollmentRels is where relationship names are stored.
var CourseEnrollmentRels = struct {
	Course string
	User   string
}{
	Course: "Course",
	User:   "User",
}

// courseEnrollmentR is where relationships are stored.
type courseEnrollmentR struct {
	Course *Course `boil:"Course" json:"Course" toml:"Course" yaml:"Course"`
	User   *User   `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*courseEnrollmentR) NewStruct() *courseEnrollmentR {
	return &courseEnrollmentR{}
}

func (r *courseEnrollmentR) GetCourse() *Course {
	if r == nil {
		return nil
	}
	return r.Course
}

func (r *courseEnrollmentR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// courseEnrollmentL is where Load methods for each relationship are stored.
type courseEnrollmentL struct{}

var (
	courseEnrollmentAllColumns            = []string{"id", "course_id", "user_id", "finished_at", "created_at", "finished"}
	courseEnrollmentColumnsWithoutDefault = []string{"id", "course_id", "user_id"}
	courseEnrollmentColumnsWithDefault    = []string{"finished_at", "created_at", "finished"}
	courseEnrollmentPrimaryKeyColumns     = []string{"id"}
	courseEnrollmentGeneratedColumns      = []string{}
)

type (
	// CourseEnrollmentSlice is an alias for a slice of pointers to CourseEnrollment.
	// This should almost always be used instead of []CourseEnrollment.
	CourseEnrollmentSlice []*CourseEnrollment
	// CourseEnrollmentHook is the signature for custom CourseEnrollment hook methods
	CourseEnrollmentHook func(context.Context, boil.ContextExecutor, *CourseEnrollment) error

	courseEnrollmentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	courseEnrollmentType                 = reflect.TypeOf(&CourseEnrollment{})
	courseEnrollmentMapping              = queries.MakeStructMapping(courseEnrollmentType)
	courseEnrollmentPrimaryKeyMapping, _ = queries.BindMapping(courseEnrollmentType, courseEnrollmentMapping, courseEnrollmentPrimaryKeyColumns)
	courseEnrollmentInsertCacheMut       sync.RWMutex
	courseEnrollmentInsertCache          = make(map[string]insertCache)
	courseEnrollmentUpdateCacheMut       sync.RWMutex
	courseEnrollmentUpdateCache          = make(map[string]updateCache)
	courseEnrollmentUpsertCacheMut       sync.RWMutex
	courseEnrollmentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var courseEnrollmentAfterSelectMu sync.Mutex
var courseEnrollmentAfterSelectHooks []CourseEnrollmentHook

var courseEnrollmentBeforeInsertMu sync.Mutex
var courseEnrollmentBeforeInsertHooks []CourseEnrollmentHook
var courseEnrollmentAfterInsertMu sync.Mutex
var courseEnrollmentAfterInsertHooks []CourseEnrollmentHook

var courseEnrollmentBeforeUpdateMu sync.Mutex
var courseEnrollmentBeforeUpdateHooks []CourseEnrollmentHook
var courseEnrollmentAfterUpdateMu sync.Mutex
var courseEnrollmentAfterUpdateHooks []CourseEnrollmentHook

var courseEnrollmentBeforeDeleteMu sync.Mutex
var courseEnrollmentBeforeDeleteHooks []CourseEnrollmentHook
var courseEnrollmentAfterDeleteMu sync.Mutex
var courseEnrollmentAfterDeleteHooks []CourseEnrollmentHook

var courseEnrollmentBeforeUpsertMu sync.Mutex
var courseEnrollmentBeforeUpsertHooks []CourseEnrollmentHook
var courseEnrollmentAfterUpsertMu sync.Mutex
var courseEnrollmentAfterUpsertHooks []CourseEnrollmentHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *CourseEnrollment) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseEnrollmentAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *CourseEnrollment) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseEnrollmentBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *CourseEnrollment) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseEnrollmentAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *CourseEnrollment) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseEnrollmentBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *CourseEnrollment) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseEnrollmentAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *CourseEnrollment) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseEnrollmentBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *CourseEnrollment) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseEnrollmentAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *CourseEnrollment) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseEnrollmentBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *CourseEnrollment) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range courseEnrollmentAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCourseEnrollmentHook registers your hook function for all future operations.
func AddCourseEnrollmentHook(hookPoint boil.HookPoint, courseEnrollmentHook CourseEnrollmentHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		courseEnrollmentAfterSelectMu.Lock()
		courseEnrollmentAfterSelectHooks = append(courseEnrollmentAfterSelectHooks, courseEnrollmentHook)
		courseEnrollmentAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		courseEnrollmentBeforeInsertMu.Lock()
		courseEnrollmentBeforeInsertHooks = append(courseEnrollmentBeforeInsertHooks, courseEnrollmentHook)
		courseEnrollmentBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		courseEnrollmentAfterInsertMu.Lock()
		courseEnrollmentAfterInsertHooks = append(courseEnrollmentAfterInsertHooks, courseEnrollmentHook)
		courseEnrollmentAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		courseEnrollmentBeforeUpdateMu.Lock()
		courseEnrollmentBeforeUpdateHooks = append(courseEnrollmentBeforeUpdateHooks, courseEnrollmentHook)
		courseEnrollmentBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		courseEnrollmentAfterUpdateMu.Lock()
		courseEnrollmentAfterUpdateHooks = append(courseEnrollmentAfterUpdateHooks, courseEnrollmentHook)
		courseEnrollmentAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		courseEnrollmentBeforeDeleteMu.Lock()
		courseEnrollmentBeforeDeleteHooks = append(courseEnrollmentBeforeDeleteHooks, courseEnrollmentHook)
		courseEnrollmentBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		courseEnrollmentAfterDeleteMu.Lock()
		courseEnrollmentAfterDeleteHooks = append(courseEnrollmentAfterDeleteHooks, courseEnrollmentHook)
		courseEnrollmentAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		courseEnrollmentBeforeUpsertMu.Lock()
		courseEnrollmentBeforeUpsertHooks = append(courseEnrollmentBeforeUpsertHooks, courseEnrollmentHook)
		courseEnrollmentBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		courseEnrollmentAfterUpsertMu.Lock()
		courseEnrollmentAfterUpsertHooks = append(courseEnrollmentAfterUpsertHooks, courseEnrollmentHook)
		courseEnrollmentAfterUpsertMu.Unlock()
	}
}

// One returns a single courseEnrollment record from the query.
func (q courseEnrollmentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*CourseEnrollment, error) {
	o := &CourseEnrollment{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for course_enrollments")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all CourseEnrollment records from the query.
func (q courseEnrollmentQuery) All(ctx context.Context, exec boil.ContextExecutor) (CourseEnrollmentSlice, error) {
	var o []*CourseEnrollment

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to CourseEnrollment slice")
	}

	if len(courseEnrollmentAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all CourseEnrollment records in the query.
func (q courseEnrollmentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count course_enrollments rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q courseEnrollmentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if course_enrollments exists")
	}

	return count > 0, nil
}

// Course pointed to by the foreign key.
func (o *CourseEnrollment) Course(mods ...qm.QueryMod) courseQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CourseID),
	}

	queryMods = append(queryMods, mods...)

	return Courses(queryMods...)
}

// User pointed to by the foreign key.
func (o *CourseEnrollment) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadCourse allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (courseEnrollmentL) LoadCourse(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCourseEnrollment interface{}, mods queries.Applicator) error {
	var slice []*CourseEnrollment
	var object *CourseEnrollment

	if singular {
		var ok bool
		object, ok = maybeCourseEnrollment.(*CourseEnrollment)
		if !ok {
			object = new(CourseEnrollment)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCourseEnrollment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCourseEnrollment))
			}
		}
	} else {
		s, ok := maybeCourseEnrollment.(*[]*CourseEnrollment)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCourseEnrollment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCourseEnrollment))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &courseEnrollmentR{}
		}
		args[object.CourseID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &courseEnrollmentR{}
			}

			args[obj.CourseID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`courses`),
		qm.WhereIn(`courses.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Course")
	}

	var resultSlice []*Course
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Course")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for courses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for courses")
	}

	if len(courseAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Course = foreign
		if foreign.R == nil {
			foreign.R = &courseR{}
		}
		foreign.R.CourseEnrollments = append(foreign.R.CourseEnrollments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CourseID == foreign.ID {
				local.R.Course = foreign
				if foreign.R == nil {
					foreign.R = &courseR{}
				}
				foreign.R.CourseEnrollments = append(foreign.R.CourseEnrollments, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (courseEnrollmentL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeCourseEnrollment interface{}, mods queries.Applicator) error {
	var slice []*CourseEnrollment
	var object *CourseEnrollment

	if singular {
		var ok bool
		object, ok = maybeCourseEnrollment.(*CourseEnrollment)
		if !ok {
			object = new(CourseEnrollment)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCourseEnrollment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCourseEnrollment))
			}
		}
	} else {
		s, ok := maybeCourseEnrollment.(*[]*CourseEnrollment)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCourseEnrollment)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCourseEnrollment))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &courseEnrollmentR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &courseEnrollmentR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CourseEnrollments = append(foreign.R.CourseEnrollments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CourseEnrollments = append(foreign.R.CourseEnrollments, local)
				break
			}
		}
	}

	return nil
}

// SetCourse of the courseEnrollment to the related item.
// Sets o.R.Course to related.
// Adds o to related.R.CourseEnrollments.
func (o *CourseEnrollment) SetCourse(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Course) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"course_enrollments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"course_id"}),
		strmangle.WhereClause("\"", "\"", 2, courseEnrollmentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CourseID = related.ID
	if o.R == nil {
		o.R = &courseEnrollmentR{
			Course: related,
		}
	} else {
		o.R.Course = related
	}

	if related.R == nil {
		related.R = &courseR{
			CourseEnrollments: CourseEnrollmentSlice{o},
		}
	} else {
		related.R.CourseEnrollments = append(related.R.CourseEnrollments, o)
	}

	return nil
}

// SetUser of the courseEnrollment to the related item.
// Sets o.R.User to related.
// Adds o to related.R.CourseEnrollments.
func (o *CourseEnrollment) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"course_enrollments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, courseEnrollmentPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &courseEnrollmentR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			CourseEnrollments: CourseEnrollmentSlice{o},
		}
	} else {
		related.R.CourseEnrollments = append(related.R.CourseEnrollments, o)
	}

	return nil
}

// CourseEnrollments retrieves all the records using an executor.
func CourseEnrollments(mods ...qm.QueryMod) courseEnrollmentQuery {
	mods = append(mods, qm.From("\"course_enrollments\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"course_enrollments\".*"})
	}

	return courseEnrollmentQuery{q}
}

// FindCourseEnrollment retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCourseEnrollment(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*CourseEnrollment, error) {
	courseEnrollmentObj := &CourseEnrollment{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"course_enrollments\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, courseEnrollmentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from course_enrollments")
	}

	if err = courseEnrollmentObj.doAfterSelectHooks(ctx, exec); err != nil {
		return courseEnrollmentObj, err
	}

	return courseEnrollmentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CourseEnrollment) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no course_enrollments provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(courseEnrollmentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	courseEnrollmentInsertCacheMut.RLock()
	cache, cached := courseEnrollmentInsertCache[key]
	courseEnrollmentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			courseEnrollmentAllColumns,
			courseEnrollmentColumnsWithDefault,
			courseEnrollmentColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(courseEnrollmentType, courseEnrollmentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(courseEnrollmentType, courseEnrollmentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"course_enrollments\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"course_enrollments\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into course_enrollments")
	}

	if !cached {
		courseEnrollmentInsertCacheMut.Lock()
		courseEnrollmentInsertCache[key] = cache
		courseEnrollmentInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the CourseEnrollment.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CourseEnrollment) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	courseEnrollmentUpdateCacheMut.RLock()
	cache, cached := courseEnrollmentUpdateCache[key]
	courseEnrollmentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			courseEnrollmentAllColumns,
			courseEnrollmentPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update course_enrollments, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"course_enrollments\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, courseEnrollmentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(courseEnrollmentType, courseEnrollmentMapping, append(wl, courseEnrollmentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update course_enrollments row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for course_enrollments")
	}

	if !cached {
		courseEnrollmentUpdateCacheMut.Lock()
		courseEnrollmentUpdateCache[key] = cache
		courseEnrollmentUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q courseEnrollmentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for course_enrollments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for course_enrollments")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CourseEnrollmentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), courseEnrollmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"course_enrollments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, courseEnrollmentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in courseEnrollment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all courseEnrollment")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CourseEnrollment) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no course_enrollments provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(courseEnrollmentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	courseEnrollmentUpsertCacheMut.RLock()
	cache, cached := courseEnrollmentUpsertCache[key]
	courseEnrollmentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			courseEnrollmentAllColumns,
			courseEnrollmentColumnsWithDefault,
			courseEnrollmentColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			courseEnrollmentAllColumns,
			courseEnrollmentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert course_enrollments, could not build update column list")
		}

		ret := strmangle.SetComplement(courseEnrollmentAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(courseEnrollmentPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert course_enrollments, could not build conflict column list")
			}

			conflict = make([]string, len(courseEnrollmentPrimaryKeyColumns))
			copy(conflict, courseEnrollmentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"course_enrollments\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(courseEnrollmentType, courseEnrollmentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(courseEnrollmentType, courseEnrollmentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert course_enrollments")
	}

	if !cached {
		courseEnrollmentUpsertCacheMut.Lock()
		courseEnrollmentUpsertCache[key] = cache
		courseEnrollmentUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single CourseEnrollment record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CourseEnrollment) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no CourseEnrollment provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), courseEnrollmentPrimaryKeyMapping)
	sql := "DELETE FROM \"course_enrollments\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from course_enrollments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for course_enrollments")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q courseEnrollmentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no courseEnrollmentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from course_enrollments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for course_enrollments")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CourseEnrollmentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(courseEnrollmentBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), courseEnrollmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"course_enrollments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, courseEnrollmentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from courseEnrollment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for course_enrollments")
	}

	if len(courseEnrollmentAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CourseEnrollment) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindCourseEnrollment(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CourseEnrollmentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CourseEnrollmentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), courseEnrollmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"course_enrollments\".* FROM \"course_enrollments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, courseEnrollmentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CourseEnrollmentSlice")
	}

	*o = slice

	return nil
}

// CourseEnrollmentExists checks if the CourseEnrollment row exists.
func CourseEnrollmentExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"course_enrollments\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if course_enrollments exists")
	}

	return exists, nil
}

// Exists checks if the CourseEnrollment row exists.
func (o *CourseEnrollment) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return CourseEnrollmentExists(ctx, exec, o.ID)
}
