// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Flag is an object representing the database table.
type Flag struct {
	ID          string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ChallengeID string    `boil:"challenge_id" json:"challenge_id" toml:"challenge_id" yaml:"challenge_id"`
	Type        string    `boil:"type" json:"type" toml:"type" yaml:"type"`
	Flag        string    `boil:"flag" json:"flag" toml:"flag" yaml:"flag"`
	FlagPrefix  string    `boil:"flag_prefix" json:"flag_prefix" toml:"flag_prefix" yaml:"flag_prefix"`
	FlagSuffix  string    `boil:"flag_suffix" json:"flag_suffix" toml:"flag_suffix" yaml:"flag_suffix"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *flagR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L flagL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FlagColumns = struct {
	ID          string
	ChallengeID string
	Type        string
	Flag        string
	FlagPrefix  string
	FlagSuffix  string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "id",
	ChallengeID: "challenge_id",
	Type:        "type",
	Flag:        "flag",
	FlagPrefix:  "flag_prefix",
	FlagSuffix:  "flag_suffix",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var FlagTableColumns = struct {
	ID          string
	ChallengeID string
	Type        string
	Flag        string
	FlagPrefix  string
	FlagSuffix  string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "flags.id",
	ChallengeID: "flags.challenge_id",
	Type:        "flags.type",
	Flag:        "flags.flag",
	FlagPrefix:  "flags.flag_prefix",
	FlagSuffix:  "flags.flag_suffix",
	CreatedAt:   "flags.created_at",
	UpdatedAt:   "flags.updated_at",
}

// Generated where

var FlagWhere = struct {
	ID          whereHelperstring
	ChallengeID whereHelperstring
	Type        whereHelperstring
	Flag        whereHelperstring
	FlagPrefix  whereHelperstring
	FlagSuffix  whereHelperstring
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpernull_Time
}{
	ID:          whereHelperstring{field: "\"flags\".\"id\""},
	ChallengeID: whereHelperstring{field: "\"flags\".\"challenge_id\""},
	Type:        whereHelperstring{field: "\"flags\".\"type\""},
	Flag:        whereHelperstring{field: "\"flags\".\"flag\""},
	FlagPrefix:  whereHelperstring{field: "\"flags\".\"flag_prefix\""},
	FlagSuffix:  whereHelperstring{field: "\"flags\".\"flag_suffix\""},
	CreatedAt:   whereHelpertime_Time{field: "\"flags\".\"created_at\""},
	UpdatedAt:   whereHelpernull_Time{field: "\"flags\".\"updated_at\""},
}

// FlagRels is where relationship names are stored.
var FlagRels = struct {
	Challenge string
}{
	Challenge: "Challenge",
}

// flagR is where relationships are stored.
type flagR struct {
	Challenge *Challenge `boil:"Challenge" json:"Challenge" toml:"Challenge" yaml:"Challenge"`
}

// NewStruct creates a new relationship struct
func (*flagR) NewStruct() *flagR {
	return &flagR{}
}

func (r *flagR) GetChallenge() *Challenge {
	if r == nil {
		return nil
	}
	return r.Challenge
}

// flagL is where Load methods for each relationship are stored.
type flagL struct{}

var (
	flagAllColumns            = []string{"id", "challenge_id", "type", "flag", "flag_prefix", "flag_suffix", "created_at", "updated_at"}
	flagColumnsWithoutDefault = []string{"id", "challenge_id", "type", "flag", "flag_prefix", "flag_suffix"}
	flagColumnsWithDefault    = []string{"created_at", "updated_at"}
	flagPrimaryKeyColumns     = []string{"id"}
	flagGeneratedColumns      = []string{}
)

type (
	// FlagSlice is an alias for a slice of pointers to Flag.
	// This should almost always be used instead of []Flag.
	FlagSlice []*Flag
	// FlagHook is the signature for custom Flag hook methods
	FlagHook func(context.Context, boil.ContextExecutor, *Flag) error

	flagQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	flagType                 = reflect.TypeOf(&Flag{})
	flagMapping              = queries.MakeStructMapping(flagType)
	flagPrimaryKeyMapping, _ = queries.BindMapping(flagType, flagMapping, flagPrimaryKeyColumns)
	flagInsertCacheMut       sync.RWMutex
	flagInsertCache          = make(map[string]insertCache)
	flagUpdateCacheMut       sync.RWMutex
	flagUpdateCache          = make(map[string]updateCache)
	flagUpsertCacheMut       sync.RWMutex
	flagUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var flagAfterSelectMu sync.Mutex
var flagAfterSelectHooks []FlagHook

var flagBeforeInsertMu sync.Mutex
var flagBeforeInsertHooks []FlagHook
var flagAfterInsertMu sync.Mutex
var flagAfterInsertHooks []FlagHook

var flagBeforeUpdateMu sync.Mutex
var flagBeforeUpdateHooks []FlagHook
var flagAfterUpdateMu sync.Mutex
var flagAfterUpdateHooks []FlagHook

var flagBeforeDeleteMu sync.Mutex
var flagBeforeDeleteHooks []FlagHook
var flagAfterDeleteMu sync.Mutex
var flagAfterDeleteHooks []FlagHook

var flagBeforeUpsertMu sync.Mutex
var flagBeforeUpsertHooks []FlagHook
var flagAfterUpsertMu sync.Mutex
var flagAfterUpsertHooks []FlagHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Flag) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flagAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Flag) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flagBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Flag) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flagAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Flag) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flagBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Flag) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flagAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Flag) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flagBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Flag) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flagAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Flag) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flagBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Flag) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range flagAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFlagHook registers your hook function for all future operations.
func AddFlagHook(hookPoint boil.HookPoint, flagHook FlagHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		flagAfterSelectMu.Lock()
		flagAfterSelectHooks = append(flagAfterSelectHooks, flagHook)
		flagAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		flagBeforeInsertMu.Lock()
		flagBeforeInsertHooks = append(flagBeforeInsertHooks, flagHook)
		flagBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		flagAfterInsertMu.Lock()
		flagAfterInsertHooks = append(flagAfterInsertHooks, flagHook)
		flagAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		flagBeforeUpdateMu.Lock()
		flagBeforeUpdateHooks = append(flagBeforeUpdateHooks, flagHook)
		flagBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		flagAfterUpdateMu.Lock()
		flagAfterUpdateHooks = append(flagAfterUpdateHooks, flagHook)
		flagAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		flagBeforeDeleteMu.Lock()
		flagBeforeDeleteHooks = append(flagBeforeDeleteHooks, flagHook)
		flagBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		flagAfterDeleteMu.Lock()
		flagAfterDeleteHooks = append(flagAfterDeleteHooks, flagHook)
		flagAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		flagBeforeUpsertMu.Lock()
		flagBeforeUpsertHooks = append(flagBeforeUpsertHooks, flagHook)
		flagBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		flagAfterUpsertMu.Lock()
		flagAfterUpsertHooks = append(flagAfterUpsertHooks, flagHook)
		flagAfterUpsertMu.Unlock()
	}
}

// One returns a single flag record from the query.
func (q flagQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Flag, error) {
	o := &Flag{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for flags")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Flag records from the query.
func (q flagQuery) All(ctx context.Context, exec boil.ContextExecutor) (FlagSlice, error) {
	var o []*Flag

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Flag slice")
	}

	if len(flagAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Flag records in the query.
func (q flagQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count flags rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q flagQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if flags exists")
	}

	return count > 0, nil
}

// Challenge pointed to by the foreign key.
func (o *Flag) Challenge(mods ...qm.QueryMod) challengeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChallengeID),
	}

	queryMods = append(queryMods, mods...)

	return Challenges(queryMods...)
}

// LoadChallenge allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (flagL) LoadChallenge(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFlag interface{}, mods queries.Applicator) error {
	var slice []*Flag
	var object *Flag

	if singular {
		var ok bool
		object, ok = maybeFlag.(*Flag)
		if !ok {
			object = new(Flag)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFlag)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFlag))
			}
		}
	} else {
		s, ok := maybeFlag.(*[]*Flag)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFlag)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFlag))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &flagR{}
		}
		args[object.ChallengeID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &flagR{}
			}

			args[obj.ChallengeID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`challenges`),
		qm.WhereIn(`challenges.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Challenge")
	}

	var resultSlice []*Challenge
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Challenge")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for challenges")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for challenges")
	}

	if len(challengeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Challenge = foreign
		if foreign.R == nil {
			foreign.R = &challengeR{}
		}
		foreign.R.Flags = append(foreign.R.Flags, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ChallengeID == foreign.ID {
				local.R.Challenge = foreign
				if foreign.R == nil {
					foreign.R = &challengeR{}
				}
				foreign.R.Flags = append(foreign.R.Flags, local)
				break
			}
		}
	}

	return nil
}

// SetChallenge of the flag to the related item.
// Sets o.R.Challenge to related.
// Adds o to related.R.Flags.
func (o *Flag) SetChallenge(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Challenge) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"flags\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"challenge_id"}),
		strmangle.WhereClause("\"", "\"", 2, flagPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ChallengeID = related.ID
	if o.R == nil {
		o.R = &flagR{
			Challenge: related,
		}
	} else {
		o.R.Challenge = related
	}

	if related.R == nil {
		related.R = &challengeR{
			Flags: FlagSlice{o},
		}
	} else {
		related.R.Flags = append(related.R.Flags, o)
	}

	return nil
}

// Flags retrieves all the records using an executor.
func Flags(mods ...qm.QueryMod) flagQuery {
	mods = append(mods, qm.From("\"flags\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"flags\".*"})
	}

	return flagQuery{q}
}

// FindFlag retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFlag(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Flag, error) {
	flagObj := &Flag{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"flags\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, flagObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from flags")
	}

	if err = flagObj.doAfterSelectHooks(ctx, exec); err != nil {
		return flagObj, err
	}

	return flagObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Flag) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no flags provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(flagColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	flagInsertCacheMut.RLock()
	cache, cached := flagInsertCache[key]
	flagInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			flagAllColumns,
			flagColumnsWithDefault,
			flagColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(flagType, flagMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(flagType, flagMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"flags\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"flags\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into flags")
	}

	if !cached {
		flagInsertCacheMut.Lock()
		flagInsertCache[key] = cache
		flagInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Flag.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Flag) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	flagUpdateCacheMut.RLock()
	cache, cached := flagUpdateCache[key]
	flagUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			flagAllColumns,
			flagPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update flags, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"flags\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, flagPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(flagType, flagMapping, append(wl, flagPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update flags row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for flags")
	}

	if !cached {
		flagUpdateCacheMut.Lock()
		flagUpdateCache[key] = cache
		flagUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q flagQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for flags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for flags")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FlagSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"flags\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, flagPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in flag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all flag")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Flag) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no flags provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(flagColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	flagUpsertCacheMut.RLock()
	cache, cached := flagUpsertCache[key]
	flagUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			flagAllColumns,
			flagColumnsWithDefault,
			flagColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			flagAllColumns,
			flagPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert flags, could not build update column list")
		}

		ret := strmangle.SetComplement(flagAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(flagPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert flags, could not build conflict column list")
			}

			conflict = make([]string, len(flagPrimaryKeyColumns))
			copy(conflict, flagPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"flags\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(flagType, flagMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(flagType, flagMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert flags")
	}

	if !cached {
		flagUpsertCacheMut.Lock()
		flagUpsertCache[key] = cache
		flagUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Flag record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Flag) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Flag provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), flagPrimaryKeyMapping)
	sql := "DELETE FROM \"flags\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from flags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for flags")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q flagQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no flagQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from flags")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for flags")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FlagSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(flagBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"flags\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, flagPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from flag slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for flags")
	}

	if len(flagAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Flag) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFlag(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FlagSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FlagSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), flagPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"flags\".* FROM \"flags\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, flagPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in FlagSlice")
	}

	*o = slice

	return nil
}

// FlagExists checks if the Flag row exists.
func FlagExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"flags\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if flags exists")
	}

	return exists, nil
}

// Exists checks if the Flag row exists.
func (o *Flag) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FlagExists(ctx, exec, o.ID)
}
