#cloud-config

package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common
  - git

groups:
  - docker

runcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

ssh_pwauth: false
users:
  - name: mosu
    lock_passwd: true
    shell: /bin/bash
    groups: docker
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINrqJ9vWzaV1tG3kODMqfWW7owrjbpSmysT9nSR1KLSx
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: mati
    lock_passwd: true
    shell: /bin/bash
    groups: docker
    ssh_import_id:
      - gh:mateuszdrwal
    sudo: ALL=(ALL) NOPASSWD:ALL

